name: FIRMS Data Pipeline

# Trigger the workflow every hour
on:
  schedule:
    - cron: "0 * * * *"  # runs at minute 0 of every hour
  workflow_dispatch:       # allows manual trigger

jobs:
  run-firms-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      # Step 4: Run the FIRMS data pipeline
      - name: Run FIRMS Data Pipeline
        run: |
          python backend/data_pipeline.py
